services:

  postgresdb:
    image: "postgres:latest"

  presentation:
    image: ${DOCKER_REGISTRY-}presentation
    build:
      context: .
      dockerfile: src/Presentation/Dockerfile

  pyface:
    image: ${DOCKER_REGISTRY-}pyface
    build:
      context: .
      dockerfile: src/PyFace/Dockerfile

  pgadmin:
    image: elestio/pgadmin:latest

volumes:
  postgres_data:
  pgadmin_data: