# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nface.proto\x12\x04\x66\x61\x63\x65\"1\n\x14\x46\x61\x63\x65\x44\x65tectionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\n\n\x02id\x18\x02 \x01(\t\"2\n\x12\x46\x61\x63\x65\x44\x65tectionReply\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65tected\x18\x02 \x01(\x08\x32O\n\rFaceDetection\x12>\n\x06\x44\x65tect\x12\x1a.face.FaceDetectionRequest\x1a\x18.face.FaceDetectionReplyB\x16\xaa\x02\x13Presentation.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\023Presentation.Protos'
  _globals['_FACEDETECTIONREQUEST']._serialized_start=20
  _globals['_FACEDETECTIONREQUEST']._serialized_end=69
  _globals['_FACEDETECTIONREPLY']._serialized_start=71
  _globals['_FACEDETECTIONREPLY']._serialized_end=121
  _globals['_FACEDETECTION']._serialized_start=123
  _globals['_FACEDETECTION']._serialized_end=202
# @@protoc_insertion_point(module_scope)
